In [22]:
import os
from sklearn.cluster import KMeans 

os.chdir('/Users/nagendrak/Desktop')
import pandas as pd
data=pd.read_csv("rmasterdata.csv", delimiter = ',' , encoding = 'unicode_escape',header=0, engine='python')

In [ ]:
def pscore(data):
    data_small=data[["f_qty_item_ordered","turnover_bu_mdl_tax_ex","events","sessions"]]
    [data_small[col].update((data_small[col] - data_small[col].min()) / (data_small[col].max() - data_small[col].min())) for col in data_small.columns]
    data_small['pscore']=(data_small['f_qty_item_ordered']+data_small['turnover_bu_mdl_tax_ex']+data_small['events']+data_small['sessions'])/4
    data['pscore']=data_small['pscore']

In [16]:
def topsellers(data):
    data_smal=data[["f_qty_item_ordered","turnover_bu_mdl_tax_ex","events","sessions"]]
    [data_smal[col].update((data_smal[col] - data_smal[col].min()) / (data_smal[col].max() - data_smal[col].min())) for col in data_smal.columns]
    clusterNum = 2
    k_means = KMeans(init = "k-means++", n_clusters = clusterNum, n_init = 50)
    k_means.fit(data_smal)
    labels = k_means.labels_
    data['cluster']=labels


In [35]:
data_smal=data[["f_qty_item_ordered","turnover_bu_mdl_tax_ex","events","sessions"]]
[data_smal[col].update((data_smal[col] - data_smal[col].min()) / (data_smal[col].max() - data_smal[col].min())) for col in data_smal.columns]
clusterNum = 2
k_means = KMeans(init = "random", n_clusters = clusterNum, n_init = 50)
k_means.fit(data_smal)
labels = k_means.labels_
k_means.cluster_centers_.ravel()

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


array([0.14648582, 0.15693107, 0.12630899, 0.15475604, 0.01463374,
       0.01598338, 0.00790698, 0.00938861])

In [79]:
import numpy as np

my_list = list(k_means.cluster_centers_)
new_list=np.array(my_list)
new_list
final <- Dataframe[Dataframe['cluster'] == top_sellers,1:11]
Data[data['cluster']==new_list[0]]


array([[0.14648582, 0.15693107, 0.12630899, 0.15475604],
       [0.01463374, 0.01598338, 0.00790698, 0.00938861]])

In [87]:
labels=new_list[0]
labels

array([0.14648582, 0.15693107, 0.12630899, 0.15475604])

In [67]:
k_means.cluster_centers_.ravel().apply(max, axis=0)


AttributeError: 'list' object has no attribute 'apply'

In [38]:
top_sellers= apply(max(k_means.cluster_centers_.all()), axis = 1) 


TypeError: 'numpy.bool_' object is not iterable

In [46]:
import numpy as np
df['add'] = max(k_means.cluster_centers_.apply(np.sum, axis = 1)) 


AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [ ]:
top_sellers = which.max(apply(km_rc$centroids, 1, sum))
low_sellers = which.min(apply(km_rc$centroids, 1, sum))
Dataframe$cluster <- km_rc$clusters
final <- Dataframe[Dataframe['cluster'] == top_sellers,1:11]